port: "COM6"
baud_rate: 9600
screenshot:
  item_list:
    x: 56
    y: 120
    width: 232
    height: 300
  item_offers_list_without_buttons:
    x: 56
    y: 96
    width: 232
    height: 345
  item_offers_list_with_buttons:
    x: 56
    y: 120
    width: 232
    height: 300
  item_offers_list_buttons:
    x: 56
    y: 96
    width: 232
    height: 20
  item1:
    x: 63
    y: 98
    width: 232
    height: 30
  item2:
    x: 63
    y: 98
    width: 232
    height: 30
click:
  back:
    x: 40
    y: 80
  button1:
    x: 35
    y: 100
  button2:
    x: 62
    y: 100
  button3:
    x: 95
    y: 100
  button4:
    x: 120
    y: 100
  button5:
    x: 152
    y: 100
  button6:
    x: 180
    y: 100
  item1:
    x: 124
    y: 128
  item2:
    x: 125
    y: 155
  item3:
    x: 124
    y: 185
  item4:
    x: 124
    y: 215
  item5:
    x: 124
    y: 245
  item6:
    x: 124
    y: 275
  item7:
    x: 124
    y: 305
  item8:
    x: 124
    y: 335
  item9:
    x: 124
    y: 365
  scroll:
    x: 305
    y: 426