port: "COM6"
baud_rate: 9600
screenshot:
  item_list:
    x: 120
    y: 0
    width: 260
    height: 276
  item_offers_list_without_buttons:
    x: 56
    y: 96
    width: 232
    height: 345
  item_offers_list_with_buttons:
    x: 56
    y: 120
    width: 232
    height: 300
  item_offers_list_buttons:
    x: 56
    y: 96
    width: 232
    height: 20
  item1:
    x: 63
    y: 98
    width: 232
    height: 30
  item2:
    x: 63
    y: 98
    width: 232
    height: 30
click:
  back:
    x: 25
    y: 8
  button1:
    x: 35
    y: 100
  button2:
    x: 62
    y: 100
  button3:
    x: 95
    y: 100
  button4:
    x: 120
    y: 100
  button5:
    x: 152
    y: 100
  button6:
    x: 180
    y: 100
  item1:
    x: 125
    y: 55
  item2:
    x: 125
    y: 85
  item3:
    x: 124
    y: 115
  item4:
    x: 124
    y: 145
  item5:
    x: 124
    y: 175
  item6:
    x: 124
    y: 205
  item7:
    x: 124
    y: 235
  item8:
    x: 124
    y: 265
  item9:
    x: 124
    y: 295
  scroll:
    x: 290
    y: 354