version: '3.8'

services:
  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./prometheus-datasource.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./dashboard-provider.yaml:/etc/grafana/provisioning/dashboards/dashboard-provider.yaml
      - ./grafana-dashboard.json:/etc/grafana/provisioning/dashboards/grafana-dashboard.json
    restart: unless-stopped 