services:
  - type: web
    name: shnyr-web-viewer
    env: docker
    plan: free
    buildCommand: docker build -t shnyr-web-viewer .
    startCommand: docker run -p $PORT:8080 shnyr-web-viewer
    envVars:
      - key: PORT
        value: 8080
      - key: HOST
        value: 0.0.0.0
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
    healthCheckPath: /
    autoDeploy: true
    dockerfilePath: ./Dockerfile 