services:
  - type: web
    name: shnyr-web-viewer
    env: go
    plan: free
    buildCommand: go build -o main cmd/web_viewer/main.go
    startCommand: ./main
    envVars:
      - key: PORT
        value: 8080
      - key: HOST
        value: 0.0.0.0
      - key: DB_HOST
        value: 108.181.194.102
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: root
      - key: DB_NAME
        value: octopus
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: grafana-dashboard
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.grafana
    envVars:
      - key: GF_SECURITY_ADMIN_PASSWORD
        value: admin123
      - key: GF_INSTALL_PLUGINS
        value: grafana-piechart-panel
      - key: GF_SERVER_SERVE_FROM_SUB_PATH
        value: true
      - key: GF_SERVER_ROOT_URL
        value: https://grafana-dashboard.onrender.com/
      - key: GF_SERVER_DOMAIN
        value: grafana-dashboard.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true 