{
 "title": "Gold Coin Prices Monitoring",
 "tags": [
  "shnyr",
  "gold-coin"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Average Min 3 Prices",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "gold_coin_avg_min_3_prices", "legendFormat": "{{category}}" }
   ]
  },
  {
   "title": "Min Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "gold_coin_min_price", "legendFormat": "{{category}}" }
   ]
  },
  {
   "title": "Max Price of Min 3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "gold_coin_max_price_of_min_3", "legendFormat": "{{category}}" }
   ]
  },
  {
   "title": "Prices Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "gold_coin_prices_count", "legendFormat": "{{category}}" }
   ]
  }
 ]
}